### ISSUE TITLE
Make transition duration configurable

### ISSUE THREAD

**Issue by NielsJanssen** [guanzo/vue-smooth-height#2]
Love this mixin you've made, but the animation is a bit too slow for the project I'm working on. Could you make the height transition duration configurable? Preferably in MS.

**Comment by guanzo** [comment]
This is something I've been considering. You're able to customize the duration through CSS but then there's 2 separate places that are dictating the transition. I'll add a `transition` option where you can pass any valid CSS transition property, including the duration.

**Comment by guanzo** [comment]
This has been added in v1.5. You can specify any valid CSS `transition` property. 
Example usage:
```
this.$smoothElement({
	el: '.container',
	transition: 'height .35s linear 500ms'
})
```
