### ISSUE TITLE
Take Vue transitions into account

### ISSUE THREAD

**Issue by JelleScheer** [guanzo/vue-smooth-height#3]
Foremost; thanks for this amazing tool, it works really great!

It would be awesome if Vue transitions would be taken into account. Example:

If I have an element that slides in on click, vue-smooth-height succesfully animates the height of the box to match the new height. When the box gets closed, the element slides out but vue-smooth-height doesn't animate it. It will just kinda 'jump-close' the box when the Vue transition is over.

Hopefully this makes sense, if not I'll make a short clip to demonstrate it.

**Comment by guanzo** [comment]
Hey Jelle,

Great suggestion. It does make sense, but if you could still make a demo of the issue, that'd be great.

**Comment by guanzo** [comment]
This functionality has been added in v1.6. Check out the updated demo in the README. I can't guarantee that it performs flawlessly with arbitrary amounts of nested children and their transitions, but for most simple cases it works fine.

**Comment by JelleScheer** [comment]
Awesome! :D
