### ISSUE TITLE
Dist has ES6 syntax

### ISSUE THREAD

**Issue by verstoff** [guanzo/vue-smooth-height#6]
Hello.
It seems the dependency "parse-css-transition" contains the syntax that needs to be processed through babel (destructuring assignment) but it doesn't:
https://github.com/guanzo/vue-smooth-height/blob/f0f2d889bce9ac34b695cb10314a7b3adf1c6fb9/dist/vue-smooth-height.js#L113

**Comment by verstoff** [comment]
There are even fork:
https://github.com/onrunning/vue-smooth-height

**Comment by guanzo** [comment]
Good catch, sorry about that. I just published a fix to npm.
